<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link href="{{ public_path('css/cssPDF.css') }}" rel="stylesheet">
</head>
<body>
<p>
    CONVENIO TRANSACCIONAL DE DESOCUPACIÓN Y ENTREGA de un predio urbano ubicado en esta Ciudad, que celebra la señora ILEANA VALERIA RAVELL CANUL, como “LA PARTE PROPIETARIA” y por otro lado, el señor DAYRINE PONCE MARTÍNEZ, como “LA PARTE OCUPANTE”, lo que llevan a cabo al tenor de las siguientes: 
---------------------------------------------------- C L Á U S U L A S ---------------------------------------------------
PRIMERA.- Declara la señora ILEANA VALERIA RAVELL CANUL, que es legítima propietaria, en pleno dominio y posesión, del predio urbano de la Calle sesenta y cinco letra “B” número quinientos diecinueve de la localidad y municipio de Mérida, Yucatán, descrito de la manera siguiente siguiente: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
“PREDIO URBANO UBICADO EN LA SECCIÓN CATASTRAL DOCE, MANZANA CIENTO SETENTA Y SEIS DE LA LOCALIDAD Y MUNICIPIO DE MÉRIDA, ESTADO DE YUCATÁN, MARCADO CON EL NÚMERO QUINIENTOS DIECINUEVE DE LA CALLE SESENTA Y CINCO LETRA B, CON LA EXTENSION DE DIEZ METROS DE FRENTE POR VEINTIOCHO METROS OCHENTA CENTIMETROS DE FONDO, DE FORMA IRREGULAR, CUYO PERIMETRO SE DESCRIBE CON LAS SIGUIENTES MEDIDAS PARCIALES: PARTIENDO DEL VERTICE DEL ANGULO SESENTA DEL PREDIO Y DIRIGIENDOSE HACIA EL NOROESTE, MIDE VEINTIOCHO METROS OCHENTA CENTIMETROS; DE ESTE PUNTO HACIA EL NORESTE, MIDE VEINTE METROS; DE AQUI HACIA EL SURESTE, MIDE VEINTITRES METROS SESENTA CENTIMETROS SOBRE LA CALLE CIEN; DE AQUI HACIA EL SUR, CON DIRECCION HACIA EL ORIENTE, MIDE FORMANDO CHAFLAN CUATRO METROS DIEZ CENTIMETROS; Y DE ESTE PUNTO HACIA EL SUR, CON DESVIACIÓN HACIA EL PONIENTE, HASTA LLEGAR EL PUNTO DE PARTIDA Y CERRAR EL PERIMETRO, SOBRE LA CALLE SESENTA Y CINCO B, QUE ES EL FRENTE MIDE DIEZ METROS; CON UNA SUPERFICIE DE CUATROCIENTOS TREINTA METROS CUADRADOS, Y CON LOS SIGUIENTES LINDEROS: AL NOROESTE, EL PREDIO NUMERO QUINIENTOS CUARENTA Y NUEVE DE LA CALLE CIEN; PARTE EN PARTE EL PREDIO NUMERO QUINIENTOS DIECINUEVE LETRA A, DE LA CALLE SESENTA Y CINCO B; QUE SE DESCRIBIRA Y DESLINDARA INMEDIATAMENTE A CONTINUACION: AL NORESTE, LA CALLE CIEN; AL SURESTE, LA CALLE SESENTA Y CINCO LETRA B; Y AL SUROESTE, EL PREDIO NUMERO QUINIENTOS DIECINUEVE LETRA A DE LA CALLE SESENTA Y CINCO B.”. “LA  PARTE PROPIETARIA”, manifiesta que en el bien inmueble descrito y deslindado en el párrafo anterior, se encuentran físicamente dividido en varios departamentos y el departamento objeto del presente convenio, se le denomina convencionalmente como “DEPARTAMENTO SEIS”. - - - - - - - - - - 
SEGUNDA.- “LA PARTE OCUPANTE” reconoce y declara expresamente que ocupa el inmueble descrito y deslindado en el apartado que antecede sin título jurídico alguno, por lo que se obliga y compromete a restituirlo y entregarlo totalmente desocupado a favor de “LA PARTE PROPIETARIA” dentro de un plazo de DOCE MESES, contado a partir del día dieciocho de diciembre de dos mil veinticinco, el cual concluirá, sin necesidad de requerimiento previo, el día dieciocho de diciembre de dos mil veintiséis, pudiendo dicho plazo ser prorrogado únicamente mediante acuerdo expreso y por escrito entre las partes. 
Durante la vigencia del presente convenio, “LA PARTE OCUPANTE” se obliga a pagar a favor de “LA PARTE PROPIETARIA”, por concepto de renta u ocupación del inmueble, la cantidad de $6,200.00 (seis mil doscientos pesos 00/100 Moneda Nacional) mensuales, misma que deberá ser cubierta puntualmente el día dieciocho de cada mes, durante todo el tiempo que permanezca vigente el presente convenio, sin necesidad de requerimiento previo.
En el supuesto de que las partes acuerden prorrogar la vigencia del presente convenio, convienen expresamente que la renta mensual podrá ser objeto de modificación, ya sea por actualización, ajuste o incremento, atendiendo a las condiciones del mercado inmobiliario, al estado de conservación del inmueble o a cualquier otro factor que las partes estimen pertinente, debiendo quedar dicho nuevo monto asentado por escrito en el convenio modificatorio o adenda correspondiente, la cual formará parte integrante del presente instrumento y será obligatoria para ambas partes.
La entrega del inmueble deberá realizarse en el mismo estado físico, de conservación y funcionamiento en que actualmente se encuentra, incluyendo sus instalaciones, accesorios y bienes muebles, respondiendo “LA PARTE OCUPANTE” por cualquier daño, deterioro o menoscabo que resulte de su uso indebido, negligencia, descuido o mal manejo, quedando obligada a cubrir el costo de su reparación o reposición.
En el supuesto de que “LA PARTE OCUPANTE” desocupe el inmueble de manera anticipada, es decir, antes del vencimiento del plazo pactado, acepta expresamente que la cantidad de $5,000.00 (cinco mil pesos 00/100 Moneda Nacional) entregada a “LA PARTE PROPIETARIA” por concepto de depósito en garantía, quedará en favor de esta última como pena convencional, sin necesidad de declaración judicial, renunciando desde este momento a cualquier reclamación al respecto.  
Asimismo, al término del plazo convenido, o en caso de desocupación anticipada, si “LA PARTE OCUPANTE” presenta cualquier adeudo pendiente, ya sea por rentas, servicios, consumos, daños al inmueble o a sus instalaciones, o cualquier otro concepto imputable a su ocupación, deberá liquidarlo en su totalidad a más tardar un día natural previo a la entrega y restitución del inmueble, siendo condición indispensable para tener por cumplida la obligación de entrega.
La falta de pago de dichos adeudos faculta a “LA PARTE PROPIETARIA” para retener el depósito, sin perjuicio de exigir el pago de las cantidades que excedan dicho monto, conforme a derecho. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - TERCERA.- El predio mencionado únicamente podrá ser utilizado para DEPARTAMENTO, por lo que “LA PARTE OCUPANTE” no podrá destinarlo a otros usos distintos, ni tampoco ceder o trasladar la posesión del mismo sin el consentimiento dado por escrito por “LA PARTE PROPIETARIA” en cada caso. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
CUARTA.- El predio objeto de este convenio transaccional cuenta con una serie de bienes muebles que son propiedad de “LA PARTE PROPIETARIA”, los cuales de igual manera se entregan en posesión por el mismo plazo del bien inmueble, cuyo inventario ya es del conocimiento de “LA PARTE OCUPANTE”, la señora DAYRINE PONCE MARTÍNEZ, declara y otorga que se obliga y compromete a entregar los bienes muebles mencionados en el párrafo anterior a “LA PARTE PROPIETARIA” o a quien sus derechos representen, en el mismo buen estado de conservación y funcionamiento en el que se encuentran actualmente una vez que haya fenecido el plazo del presente Contrato de Arrendamiento  o su prórroga en determinado supuesto.     
En el supuesto que exista una pérdida total o algún daño a los bienes muebles e inmuebles. "LA PARTE OCUPANTE" se obliga a pagar a los cinco días naturales, contados a partir de que "LA PARTE PROPIETARIA” tenga conocimiento del hecho, el valor que estime este último, considerando los precios del mercado en la fecha respectiva. De igual manera los comparecientes pactan que “LA PARTE OCUPANTE” se hará cargo y responsable del mantenimiento del aire acondicionado que se encuentra en el predio objeto del presente convenio, mismo que se realizará cada seis meses contados a partir del inicio de su ocupación. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
QUINTA.- Si “LA PARTE PROPIETARIA” por cualquier motivo tuviera que ejecutar judicialmente esta transacción a fin de que “LA PARTE OCUPANTE” DESOCUPE Y ENTREGUE DESOCUPADO “EL INMUEBLE”, “LA PARTE OCUPANTE” pagará a “LA PARTE PROPIETARIA” por cada día que transcurra sin entregarlo, la cantidad de $500.00 (QUINIENTOS PESOS 00/100 MONEDA NACIONAL), desde el momento de la ejecución hasta que “EL INMUEBLE” sea entregado totalmente desocupado a “LA PARTE PROPIETARIA”. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
SEXTA.- Se estipula expresamente que “LA PARTE OCUPANTE” no podrá cambiar la estructura del predio en forma alguna, ni realizar mejoras ni instalaciones de ninguna especie, ni modificar las ya existentes, sin el consentimiento específico y anticipado, en cada caso otorgado por escrito por “LA PARTE PROPIETARIA”. 
Todas las obras y mejoras que “LA PARTE OCUPANTE” llevare a cabo en el predio quedarán a beneficio de “LA PARTE PROPIETARIA”, por lo que no podrán ser retiradas por “LA PARTE OCUPANTE”, ni esta tendrá derecho a cobrar ni “LA PARTE PROPIETARIA” la obligación de pagar el costo de las mismas.  
Asimismo, “LA PARTE OCUPANTE” tendrá el término de treinta días contados a partir del inicio de la vigencia del convenio para reportar a la parte propietaria cualquier desperfecto que tuviese el inmueble en sus instalaciones eléctricas, hidráulicas y sanitarias (tales como llaves de agua, focos, contactos de luz, ventanas, cerraduras, miriñaques, puertas entre otros) y quedando por lo tanto a cargo de “LA PARTE OCUPANTE” el mantenimiento que requieran las mismas con posterioridad a este plazo. En caso de que algún bien mueble sufra algún daño o desperfecto grave o referente a instalaciones eléctricas o hidráulicas, el ocupante se obliga a comunicarlo de forma inmediata a “LA PARTE PROPIETARIA” para que esté informada sobre la forma en que se procederá a la reposición  o  reparación  de  estos. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
SÉPTIMA.- “LA PARTE OCUPANTE”, reconoce haber recibido en perfectas condiciones estructurales, de funcionamiento y a su entera conformidad para servir al uso convenido respecto del bien inmueble objeto del presente convenio. Igualmente se pacta expresamente que al predio objeto de este convenio no se le causará daños ni deterioros por “LA PARTE OCUPANTE”, siendo responsable de los que se ocasionaren por su culpa, dolo o negligencia, debiendo repararlos o reponer el daño causado a más tardar a cinco días naturales posteriores. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
OCTAVA.- Queda a cargo exclusivo de “LA PARTE OCUPANTE”, el pago de contratos y consumo de cualquier otro servicio que se utilice en el inmueble objeto de esta transacción, así como es a su cargo el cuidado del mismo inmueble, sus partes y sus instalaciones para la conservación del buen estado que actualmente guarda.   
Las partes acuerdan que los servicios de energía eléctrica, internet, agua potable, calentador de agua, mantenimiento del edificio y recolección de basura serán a cargo de “LA PARTE PROPIETARIA”. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
NOVENA.- El presente convenio podrá darse por vencido anticipadamente si “LA PARTE OCUPANTE” incurriere en el incumplimiento de cualquiera de las obligaciones contraídas en este contrato. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA.- Este convenio transaccional tiene respecto de las partes toda la fuerza y validez de una sentencia ejecutoriada; es decir, de cosa juzgada, en los términos del Código de Procedimientos Civiles del Estado de Yucatán. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA PRIMERA.- La señora DAYRINE PONCE MARTÍNEZ entrega a “LA PARTE PROPIETARIA”, en este acto, la cantidad de $5,000.00 (cinco mil pesos 00/100 Moneda Nacional), misma que queda en poder de esta última en calidad de depósito en garantía, para asegurar el cumplimiento de todas y cada una de las obligaciones asumidas por “LA PARTE OCUPANTE” en el presente convenio.  
Dicho depósito será devuelto a “LA PARTE OCUPANTE” dentro de los cinco días naturales posteriores a la entrega material y jurídica del inmueble, siempre y cuando éste, así como los bienes muebles e instalaciones, sean restituidos en el mismo estado de conservación y funcionamiento en que actualmente se encuentran, y no exista adeudo alguno por concepto de servicios, consumos, daños, deterioros o cualquier otra obligación derivada del presente instrumento.
En caso de que, al momento de la entrega del inmueble, “LA PARTE OCUPANTE” presente adeudos pendientes o se detecten daños imputables a negligencia, uso indebido o falta de mantenimiento, “LA PARTE PROPIETARIA” queda expresamente facultada para aplicar total o parcialmente el depósito al pago de dichos adeudos y a la reparación de los daños correspondientes, sin necesidad de autorización adicional ni declaración judicial, lo anterior sin perjuicio del derecho de exigir el pago de las cantidades que excedan el monto del depósito, conforme a derecho. - - - - - - - - - - - - - - - 
DÉCIMA SEGUNDA.- Todos los pagos por honorarios, derechos, impuestos, y demás gastos que se causen por este convenio y su ejecución, en su caso quedan a cargo de “LA PARTE OCUPANTE”. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA TERCERA.- “LA PARTE OCUPANTE”, se obliga a cumplir con todas y cada una de las disposiciones municipales y sanitarias, a fin de que el predio se encuentre en condiciones higiénicas y habitables, siendo por su cuenta cualesquiera gastos, que fueren necesarios para cumplir con estas disposiciones, cuya infracción dará motivo también a la ejecución de este convenio transaccional. De igual manera “LA PARTE OCUPANTE” se obliga en este acto a no introducir en el bien inmueble sustancias explosivas y a no utilizar el bien inmueble en forma que constituya un perjuicio a los demás colindantes o que pudiese imputar mala reputación para el inmueble; el incumplimiento por parte de “LA PARTE OCUPANTE” a cualesquiera de estas obligaciones será suficiente para que “LA PARTE PROPIETARIA” rescinda el presente convenio. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA CUARTA.- Las comparecientes reconocen que cualquier testimonio de la presente escritura debe ser considerado título ejecutivo, por lo que para su ejecución no requiere de aprobación judicial, por tal motivo, la falta de cumplimiento de las obligaciones contraídas en la propia transacción dará derecho a la ejecución respectiva, como si fuere sentencia ejecutoriada, utilizando los medios de apremio que señala el capítulo de la Ejecución de las Sentencias del Código de Procedimientos Civiles vigente en el Estado, incluyendo la fuerza pública en caso necesario. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA QUINTA.- En caso de procedimiento judicial derivado del presente convenio, “LA PARTE OCUPANTE” acepta pagar mensualmente, en concepto de gastos y costas del procedimiento, una cantidad igual a cincuenta salarios mínimos diarios vigentes a la fecha del procedimiento. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA SEXTA.- “LA PARTE OCUPANTE” manifiesta y reconoce expresamente que única y exclusivamente en el supuesto de que incumpla con alguna de las obligaciones económicas asumidas en el presente convenio y, además, presente un adeudo exigible, así en el supuesto que se desconozca su paradero por un periodo continuo mayor a dos días naturales, sin haber dado aviso previo y fehaciente de su paradero a “LA PARTE PROPIETARIA”, autoriza de manera expresa e irrevocable a esta última para acceder al interior del inmueble objeto del presente instrumento y tomar posesión material del mismo, con la única finalidad de resguardar el bien y evitar mayores perjuicios. 
La facultad conferida en la presente cláusula no se considerará en ningún caso como despojo, toda vez que se ejerce con base en la autorización expresa de “LA PARTE OCUPANTE” y deriva del incumplimiento con adeudo previamente existente, sin perjuicio de las acciones legales que correspondan a “LA PARTE PROPIETARIA” para la recuperación de adeudos, daños o la restitución definitiva del inmueble conforme a derecho. - 
DÉCIMA SÉPTIMA.- “LA PARTE OCUPANTE” acepta y reconoce expresamente que, en el supuesto de que el inmueble objeto del presente convenio sea utilizado para la comisión de actos ilícitos y que dichos actos sean legalmente atribuibles a su responsabilidad, y como consecuencia de ello se inicie y concluya en forma definitiva un procedimiento de extinción de dominio a favor del Estado Mexicano, en perjuicio directo de “LA PARTE PROPIETARIA”, se obliga desde este momento a indemnizar plenamente a esta última.
Dicha indemnización consistirá en el pago del valor total del inmueble, obligación que nacerá a partir de la fecha en que quede firme la resolución definitiva que decrete la extinción de dominio, y se cumplirá mediante el pago del valor comercial que tenga el bien inmueble en el mercado inmobiliario al momento en que se realice el pago, valor que deberá ser determinado mediante avalúo practicado por perito valuador certificado, designado de común acuerdo por las partes, o en su defecto, por quien designe la autoridad competente.  
La presente obligación se establece sin perjuicio de las demás responsabilidades civiles, administrativas o penales a que haya lugar en contra de “LA PARTE OCUPANTE”, derivadas de los actos ilícitos que se le imputen, y tendrá el carácter de indemnización por daños y perjuicios, conforme a derecho. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA OCTAVA.- Para cualquier asunto o controversia con relación a este convenio, ambas partes contratantes se someten expresamente a la jurisdicción y competencia de los Jueces y Tribunales de esta ciudad de Mérida, Yucatán, con renuncia de cualquier fuero que la ley les conceda en razón de domicilio o vecindad. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
DÉCIMA NOVENA.- Acuerdan ambas partes: a) Que a petición de cualquiera de ellas, podrán ocurrir ante un Notario Público, a efecto de protocolizar el presente contrato, siendo a cargo de ambas los gastos y honorarios que se originen por la misma; b) Que los gastos, impuestos y honorarios de apoderados, abogados, procuradores y notarios que tenga que erogar alguna de las partes en virtud de que la otra no cumpla con alguna de las obligaciones y tenga que rescindir el contenido que este documento se refiere, será por cuenta única y exclusiva de la parte infractora. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
VIGÉSIMA.- Las partes, aceptan las obligaciones contraídas en este contrato en los términos de las anteriores cláusulas. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
VIGÉSIMA PRIMERA.- Las partes declaran y otorgan que han celebrado el convenio consignado en esta escritura, basado en la libertad de contratación que garantiza la Constitución Política de los Estados Unidos Mexicanos, la cual rige sobre cualquiera de las disposiciones legales aplicables. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
VIGÉSIMA SEGUNDA.- Todos los términos con mayúscula tendrán el significado que se les atribuye en este contrato. Los encabezados de las cláusulas se incluyen únicamente como referencia al contenido de dichas cláusulas y de ninguna manera afectarán el significado, contenido o interpretación de los acuerdos contenidos en las mismas. - - - - - - - - - - - - - - - - - - 
---------------------------------------------------- G E N E R A L E S -----------------------------------------------------
I.- La señora ILEANA VALERIA RAVELL CANUL, quien manifestó haber nacido en esta Ciudad y Municipio de Mérida, Yucatán, el dieciocho de enero del año mil novecientos setenta y tres, ser de cincuenta y tres años de edad, Empleada, Soltera y con domicilio marcado con el predio número trescientos treinta “A” de la calle veintidós letra “B” del Fraccionamiento Bugambilias de esta ciudad y municipio de Mérida, Yucatán y con Clave Única de Registro de Población RACI730118MYNVNL00.
II.- La señora DAYRINE PONCE MARTÍNEZ, quien manifestó haber nacido en la Ciudad de Matanzas, Cuba, el diecinueve de septiembre del año mil novecientos noventa y cinco, ser de treinta años de edad , con domicilio en el departamento objeto del presente convenio y con numero de pasaporte K744557, expedido por la República de Cuba.  
Y PARA CONSTANCIA Y CONFORMIDAD, SUSCRIBIMOS EN DUPLICADO E IMPRIMIMOS LA HUELLA DE NUESTRO DEDO PULGAR DERECHO, EL PRESENTE DOCUMENTO, EN LA CIUDAD DE MÉRIDA, YUCATÁN, ESTADOS UNIDOS MEXICANOS, A LOS DIECIOCHO DÍAS DEL MES DE DICIEMBRE DEL AÑO DOS MIL VEINTICINCO.

“LA PARTE PROPIETARIA”

 ILEANA VALERIA RAVELL CANUL


“LA PARTE OCUPANTE”


DAYRINE PONCE MARTÍNEZ











	

 
 


</p>
</body>
</html>